### ISSUE TITLE
Ring is incorrect when not saturated

### ISSUE THREAD

**Issue by andrew-d** [antifuchs/o#22]
If the ring isn't "saturated" - i.e. has not been filled to capacity - then the `Inspect` method (and thus the `Scan*` helpers) will incorrectly return a range that includes one value past the end of the filled ring. See the following playground link for an example:

https://play.golang.org/p/v6H-fwd26SG

**Comment by antifuchs** [comment]
I looked at this briefly, and... well... two findings:

* I had zero test coverage for Scanners (neither LIFO nor FIFO) where a ring contains less than the whole Ring's element count, as you noticed.

* FIFO and LIFO scanners are completely broken, even for the tested case - I think. The logic seems quite wrong. I'll have to look at this with a clearer head, but they seem to be iterating too far. 
 
Why anything works at all is a mystery to me! Impressive, my past self.

(This was always meant as a bit of performance art, but that it ... performs this maliciously was not intended (-:)

**Comment by antifuchs** [comment]
Boy howdy, Scanners are completely broken. I selectively mixed up FIFO (in-order) and LIFO (stack-order), and messed up all the test cases. If that wasn't hilarious enough, things are also more convoluted than they needed to be.

I have a (slightly incompatibly-typed, but probably much easier-to-grok) do-over of the thing, hope it works this time. I will make a ton of diagrams before pushing it to the main branch, that's for sure.
